version: "3.8"
services:
  api:
    build: ./api
    container_name: nle_api
    ports:
      - "8000:8000"
    environment:
      - DATA_DIR=/data
      - NLE_DATA_DIR=/data
      - PYTHONUNBUFFERED=1
      - HOST_DATA_DIR=/home/ubuntu/neuralife-agent-evaluator/data # added
    volumes:
      - ./api:/app
      - ./runner:/app/runner
      - ./data:/data
      - ./ui:/app/ui:ro
      - /home/ubuntu/neuralife-agent-evaluator/data:/home/ubuntu/neuralife-agent-evaluator/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  # ui:
  #   image: nginx:stable-alpine
  #   container_name: nle_ui
  #   volumes:
  #     - ./ui:/usr/share/nginx/html:ro
  #   ports:
  #     - "8080:80"
  #   restart: unless-stopped
